# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [17]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [18]:
print("Numpy Version:", np.__version__)
print("Numpy Configuration:", np.__config__.show())

Numpy Version: 2.2.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/s4460/anaconda3/envs/ironhack/Library/include
    lib directory: C:/Users/s4460/anaconda3/envs/ironhack/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_56qrev29w_\croot\numpy_and_numpy_base_1738155838326\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/s4460/anaconda3/envs/ironhack/Library/include
    lib directory: C:/Users/s4460/anaconda3/envs/ironhack/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_56qrev29w_\croot\numpy_and_numpy_base_1738155838326\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30158
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.2

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [19]:
a = np.random.random((2, 3, 5))  

b = np.random.randn(2, 3, 5)

c = np.random.randint(0, 10, (2, 3, 5))



### 4. Print a.


In [20]:
print(a)

[[[0.88569148 0.60141848 0.28113849 0.53658842 0.45350875]
  [0.22006461 0.49479773 0.58759606 0.37855187 0.02824943]
  [0.85206773 0.01770366 0.55187708 0.92623183 0.25645464]]

 [[0.17751357 0.60649369 0.46634734 0.66541037 0.6862339 ]
  [0.25678733 0.29727316 0.05682351 0.64389736 0.08222877]
  [0.43067028 0.38725453 0.22362116 0.51887015 0.25966876]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [21]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [22]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [23]:
same_size = a.shape == b.shape 
same_size_value = a.size == b.size  
print("Do 'a' and 'b' have the same shape?", same_size)
print("Do 'a' and 'b' have the same size?", same_size_value)


Do 'a' and 'b' have the same shape? False
Do 'a' and 'b' have the same size? True



### 8. Are you able to add a and b? Why or why not?


In [24]:
if same_size:
    result = a + b
    print("Arrays 'a' and 'b' can be added.")
    print(result)
else:
    print("Arrays 'a' and 'b' cannot be added because their shapes are different.")

Arrays 'a' and 'b' cannot be added because their shapes are different.




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [25]:
c = b.transpose(1, 2, 0) 


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [26]:
d = a + c 


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [27]:
print("Array a:\n", a)
print("Array d (a + c):\n", d)



Array a:
 [[[0.88569148 0.60141848 0.28113849 0.53658842 0.45350875]
  [0.22006461 0.49479773 0.58759606 0.37855187 0.02824943]
  [0.85206773 0.01770366 0.55187708 0.92623183 0.25645464]]

 [[0.17751357 0.60649369 0.46634734 0.66541037 0.6862339 ]
  [0.25678733 0.29727316 0.05682351 0.64389736 0.08222877]
  [0.43067028 0.38725453 0.22362116 0.51887015 0.25966876]]]
Array d (a + c):
 [[[1.88569148 1.60141848 1.28113849 1.53658842 1.45350875]
  [1.22006461 1.49479773 1.58759606 1.37855187 1.02824943]
  [1.85206773 1.01770366 1.55187708 1.92623183 1.25645464]]

 [[1.17751357 1.60649369 1.46634734 1.66541037 1.6862339 ]
  [1.25678733 1.29727316 1.05682351 1.64389736 1.08222877]
  [1.43067028 1.38725453 1.22362116 1.51887015 1.25966876]]]



### 12. Multiply a and c. Assign the result to e.


In [28]:
e = a * c 



### 13. Does e equal to a? Why or why not?


In [29]:
print("Array e (a * c):\n", e)


Array e (a * c):
 [[[0.88569148 0.60141848 0.28113849 0.53658842 0.45350875]
  [0.22006461 0.49479773 0.58759606 0.37855187 0.02824943]
  [0.85206773 0.01770366 0.55187708 0.92623183 0.25645464]]

 [[0.17751357 0.60649369 0.46634734 0.66541037 0.6862339 ]
  [0.25678733 0.29727316 0.05682351 0.64389736 0.08222877]
  [0.43067028 0.38725453 0.22362116 0.51887015 0.25966876]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [30]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)

Max value in d: 1.9262318335405988
Min value in d: 1.0177036610880474
Mean value in d: 1.4277011379181583



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [35]:
f = np.empty_like(d)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [36]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif value > d_min and value < d_mean:
                f[i, j, k] = 25
            elif value > d_mean and value < d_max:
                f[i, j, k] = 75





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [37]:
print("Array d:\n", d)
print("Array f (labeled values):\n", f)

Array d:
 [[[1.88569148 1.60141848 1.28113849 1.53658842 1.45350875]
  [1.22006461 1.49479773 1.58759606 1.37855187 1.02824943]
  [1.85206773 1.01770366 1.55187708 1.92623183 1.25645464]]

 [[1.17751357 1.60649369 1.46634734 1.66541037 1.6862339 ]
  [1.25678733 1.29727316 1.05682351 1.64389736 1.08222877]
  [1.43067028 1.38725453 1.22362116 1.51887015 1.25966876]]]
Array f (labeled values):
 [[[ 75.  75.  25.  75.  75.]
  [ 25.  75.  75.  25.  25.]
  [ 75.   0.  75. 100.  25.]]

 [[ 25.  75.  75.  75.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 75.  25.  25.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [34]:
### [your code here]